### ISSUE TITLE
["Request"] Calculations on `Duration.INFINITE` should not overflow

### ISSUE THREAD

**Issue by supersven** [arrow-kt/arrow-fx#18]
## What version are you currently using?

Latest master

## What would you like to see?

Calculations like `times` and `plus` on `Duration.INFINITE` should not overflow. Because this issue is due to calculations based on `Long`, it is not limited to `Duration.INFINITE`, but here the case is most obvious.

Additionally, it would be nice if `nanoseconds` would always be "valid" for the given `amount`. I.e. currently a large `amount` leads to `Long.MAX_VALUE` in `nanoseconds`, where a larger `nanoseconds` value would be right.

## Example

Currently
```
    "INFINITE plus one should be INFINITE" {
        val d = Duration(1L, TimeUnit.NANOSECONDS)
        Duration.INFINITE.plus(d).nanoseconds shouldBe  Duration.INFINITE.nanoseconds
    }
```
results in
```
expected: 9223372036854775807L but was: -9223372036854775808L
org.opentest4j.AssertionFailedError: expected: 9223372036854775807L but was: -9223372036854775808L
	at arrow.fx.data.DurationTest$3.invokeSuspend(DurationTest.kt:32)
	at arrow.fx.data.DurationTest$3.invoke(DurationTest.kt)
	at io.kotlintest.runner.jvm.TestCaseExecutor$executeTest$supervisorJob$1$invokeSuspend$$inlined$map$lambda$1.invokeSuspend(TestCaseExecutor.kt:130)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by nomisRev** [comment]
Closing this since we're deprecating our own `Duration`. If by the time of removal `kotlin.time.Duration` is still not stable we'll provide `Long` (milliseconds) based alternative methods.
