### ISSUE TITLE
Flaky test: arrow.fx.QueueTest

### ISSUE THREAD

**Issue by rachelcarmena** [arrow-kt/arrow-fx#225]
Error:

```
arrow.fx.QueueTest > DroppingQueue - time out peeking from an empty queue FAILED
    java.lang.AssertionError: Expected: Right((None, true)) but found: Right((None, false))
```

The only change from previous release:

```diff
-class QueueTest : UnitSpec() {
+class QueueTest : ArrowFxSpec() {
```

**Comment by rachelcarmena** [comment]
```
2020-07-22T17:22:54.3605990Z arrow.fx.QueueTest > UnboundedQueue - queue can be filled at once over capacity with takers FAILED
2020-07-22T17:22:54.3606140Z     arrow.fx.internal.TimeoutException: Duration(amount=20, timeUnit=SECONDS)
2020-07-22T17:22:54.3606260Z         at arrow.fx.typeclasses.Concurrent$waitFor$2.invoke(Concurrent.kt:1277)
2020-07-22T17:22:54.3606380Z         at arrow.fx.typeclasses.Concurrent$waitFor$2.invoke(Concurrent.kt:52)
2020-07-22T17:22:54.3606490Z         at arrow.fx.IO$flatMap$1.invoke(IO.kt:677)
2020-07-22T17:22:54.3606590Z         at arrow.fx.IO$flatMap$1.invoke(IO.kt:57)
2020-07-22T17:22:54.3606690Z         at arrow.fx.IORunLoop.loop(IORunLoop.kt:295)
2020-07-22T17:22:54.3606800Z         at arrow.fx.IORunLoop.access$loop(IORunLoop.kt:21)
2020-07-22T17:22:54.3606900Z         at arrow.fx.IORunLoop$RestartCallback.signal(IORunLoop.kt:414)
2020-07-22T17:22:54.3607010Z         at arrow.fx.IORunLoop$RestartCallback.trampoline(IORunLoop.kt:450)
2020-07-22T17:22:54.3607120Z         at arrow.fx.IORunLoop$RestartCallback$forward$$inlined$trampoline$1.run(Utils.kt:303)
2020-07-22T17:22:54.3607240Z         at arrow.fx.internal.Platform$TrampolineExecutor.immediateLoop(Utils.kt:246)
2020-07-22T17:22:54.3607600Z         at arrow.fx.internal.Platform$TrampolineExecutor.startLoop(Utils.kt:217)
2020-07-22T17:22:54.3607720Z         at arrow.fx.internal.Platform$TrampolineExecutor.execute(Utils.kt:224)
2020-07-22T17:22:54.3607840Z         at arrow.fx.internal.ForwardCancellable$cancel$1.invoke(ForwardCancellable.kt:102)
2020-07-22T17:22:54.3607950Z         at arrow.fx.internal.ForwardCancellable$cancel$2.invoke(ForwardCancellable.kt:36)
2020-07-22T17:22:54.3608070Z         at arrow.fx.internal.ForwardCancellable$cancel$2.invoke(ForwardCancellable.kt:19)
2020-07-22T17:22:54.3608170Z         at arrow.fx.IORunLoop$RestartCallback.start(IORunLoop.kt:397)
2020-07-22T17:22:54.3608280Z         at arrow.fx.IORunLoop.loop(IORunLoop.kt:218)
2020-07-22T17:22:54.3608380Z         at arrow.fx.IORunLoop.start(IORunLoop.kt:24)
2020-07-22T17:22:54.3608480Z         at arrow.fx.IO.unsafeRunAsync(IO.kt:853)
2020-07-22T17:22:54.3608580Z         at arrow.fx.IORace$race2$1.invoke(IORace.kt:248)
2020-07-22T17:22:54.3608690Z         at arrow.fx.IORace$race2$start$1$1.invoke(IORace.kt:278)
2020-07-22T17:22:54.3608800Z         at arrow.fx.IORace$race2$start$1$1.invoke(IORace.kt:14)
2020-07-22T17:22:54.3608910Z         at arrow.fx.IORunLoop.loop(IORunLoop.kt:292)
2020-07-22T17:22:54.3609010Z         at arrow.fx.IORunLoop.access$loop(IORunLoop.kt:21)
2020-07-22T17:22:54.3609110Z         at arrow.fx.IORunLoop$RestartCallback.signal(IORunLoop.kt:414)
2020-07-22T17:22:54.3609220Z         at arrow.fx.IORunLoop$RestartCallback.forward(IORunLoop.kt:442)
2020-07-22T17:22:54.3609330Z         at arrow.fx.IORunLoop$RestartCallback.invoke(IORunLoop.kt:423)
2020-07-22T17:22:54.3609440Z         at arrow.fx.IORunLoop$RestartCallback.invoke(IORunLoop.kt:364)
2020-07-22T17:22:54.3609540Z         at arrow.fx.internal.Platform$onceOnly$2.invoke(Utils.kt:147)
2020-07-22T17:22:54.3609650Z         at arrow.fx.internal.Platform$onceOnly$2.invoke(Utils.kt:28)
2020-07-22T17:22:54.3609760Z         at arrow.fx.internal.ShiftTick$run$$inlined$Continuation$1.resumeWith(Continuation.kt:159)
2020-07-22T17:22:54.3610040Z         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
2020-07-22T17:22:54.3610360Z         at arrow.fx.ExecutorServiceContinuation$resumeWith$1.run(IODispatchers.kt:46)
2020-07-22T17:22:54.3610510Z         at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
2020-07-22T17:22:54.3610630Z         at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
2020-07-22T17:22:54.3610740Z         at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
2020-07-22T17:22:54.3610850Z         at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
2020-07-22T17:22:54.3610970Z         at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:163)
```

**Comment by nomisRev** [comment]
Obsolete by Deprecation. These tests will be removed.
