### ISSUE TITLE
[arrow-fx-coroutines] Pending tests for Kotlin 1.4.0

### ISSUE THREAD

**Issue by rachelcarmena** [arrow-kt/arrow-fx#276]
These tests were disabled for Kotlin 1.4.0:

~* Compilation failures:~ Fixed in #293
  ~* EvalOnTests - "evalOn on a different context with a different ContinuationInterceptor does intercept"~
  ~* ConcurrentVarTest - "producer-consumer parallel loop"~
* Test failure:
  * ParJoinTest - concurrent flattening
```
 arrow.fx.coroutines.stream.ParJoinTest > concurrent flattening FAILED
     TimeoutException(duration=600000)
         at io.kotest.engine.ExecutorExecutionContext$executeWithTimeoutInterruption$$inlined$suspendCoroutine$lambda$1.run(ExecutorExecutionContext.kt:38)
         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
         at java.lang.Thread.run(Thread.java:748)
```

**Comment by nomisRev** [comment]
Obsolete by deprecation
